### ISSUE TITLE
Requirements: Links, Typos, Packages

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/isaac#29]
We should fix some typos (e.g.,boost version) in the [Requirements](https://github.com/ComputationalRadiationPhysics/isaac/tree/3b9c4f75dcc9a697ad320e28251bb9c9ccdf5d56#requirements) and also add
- links to projects
- package names (Debian, Arch)
- list maybe some sub-dependencies that break peoples necks during installs

**Comment by theZiz** [comment]
I added the informations except for the package names. Tbh in most cases using the git version instead of the package version is a good idea, e.g. for boost and libwebsockets. And arch users don't need the package names. If they do, they should switch to debian sid.

However there a probably dozen of (new) typos, so I will let this open to remind me to check the wall of text for such errors if I have a bit more spare time.

**Comment by theZiz** [comment]
Should be fine now. https://github.com/ComputationalRadiationPhysics/isaac/commit/677aa2cfca71836c7a68ab5a62a89b152470c1d4
